#!/usr/bin/env bash

function set_sink() {
  echo switching default
  pacmd set-default-sink $1 ||
    echo failed
  echo switching applications
  pacmd list-sink-inputs |
    awk '/index:/{print $2}' |
    xargs -r -I{} pacmd move-sink-input {} $1 ||
      echo failed
}

case "${1:-}" in
  (""|list)
    pacmd list-sinks |
      grep -E 'index:|name:'
    ;;
  ([0-9]*)
    set_sink $1
    ;;
  ("x")
    echo swapping sinks
    current_sink=$(pacmd list-sinks | sed -n -e 's/\*[[:space:]]index:[[:space:]]\([[:digit:]]\)/\1/p')
    if [ $current_sink -eq 2 ]; then
      set_sink 1
    else
      set_sink 2
    fi
    ;;
  (*)
    echo "Usage: $0 [|list|<sink name to switch to>]"
    ;;
esac
